# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x0e\x61gentic_server\">\n\x0b\x43hatRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\"/\n\x0c\x43hatResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x14\n\x12HealthCheckRequest\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xae\x01\n\rAgenticServer\x12\x43\n\x04\x43hat\x12\x1b.agentic_server.ChatRequest\x1a\x1c.agentic_server.ChatResponse\"\x00\x12X\n\x0bHealthCheck\x12\".agentic_server.HealthCheckRequest\x1a#.agentic_server.HealthCheckResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=32
  _globals['_CHATREQUEST']._serialized_end=94
  _globals['_CHATRESPONSE']._serialized_start=96
  _globals['_CHATRESPONSE']._serialized_end=143
  _globals['_HEALTHCHECKREQUEST']._serialized_start=145
  _globals['_HEALTHCHECKREQUEST']._serialized_end=165
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=167
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=204
  _globals['_AGENTICSERVER']._serialized_start=207
  _globals['_AGENTICSERVER']._serialized_end=381
# @@protoc_insertion_point(module_scope)
